```{r setupintro, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
```

# Introduction {-}

Genetic  diversity  is  an  essential  prerequisite  for  the  capacity  of  all  life  to  adapt  to  an  ever-changing environment, and trees are notorious for their large standing genetic variation. There are several ways by which genetic variation can be incorporated or reshuffled in a species, but the only way of generating truly novel genetic diversity is through mutation. Scientists have dedicated considerable efforts to understand the  roles  of  phylogeography,  local  adaptation,  speciation,  and  hybridisation  in  modulating  genetic diversity  of  tropical  trees,  however,  our  current  knowledge  of  mutational  processes  in  tropical  trees  is very  limited.  Recent  advances in  DNA  sequencing  techniques  now  allow  us  to  detect  single  point mutations with unprecedented precision, which opens up exciting possibilities in mutation research. We propose to sequence the genomes of tropical rainforest trees in French Guiana, providing, for the first time,  reference  genomes  of  three  Neotropical  rainforest  tree  species.  We  will  test  intra-individual  and inter-specific effects of low to extreme canopy sunlight exposure on the accumulation of novel mutations. The  tree  architecture  (i.e.,  the  branching  pattern)  will  represent  the  null  hypothesis  for  the  pattern  of accumulation of mutations. We will test the existence of a soma vs. germline segregation in tropical trees and the transmission of novel mutations from parent to offspring. The genomic data and knowledge to be generated in the project represent crucial information towards understanding genome evolution and its drivers  in  long-lived  organisms.  The  comparison  of  mutational  processes  among  tropical  species, combined  with  the  potential retention  of  mutations  in  offspring  should  be  invaluable  in  assessing  the importance of mutation rates in the creation and maintenance of Neotropical diversity. *source: TreeMutation CEBA proposal*

## Ressources {-}

* [Niklas' notebook](https://onedrive.live.com/view.aspx?resid=3C16B36AC758A6DB!439537&authkey=!AHS5FemAl1Z9fYI)
* [tasks](https://github.com/sylvainschmitt/treemutation/projects/1?add_cards_query=is%3Aopen)
