```{r setupspecies, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(kableExtra)
if(knitr:::is_html_output()) options(knitr.table.format = "html") 
if(knitr:::is_latex_output()) options(knitr.table.format = "latex") 
library(tidyverse)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
```


```{r cdataspecies}
species <- read_csv(file = "data/list_species_TreeAdapt_130220b.csv") %>% 
  rename(Family = Famille,
         Genus = Genre,
         Species = Espece,
         AnnualRings = `Annual Rings`,
         ReproductivePhenology = `Reproductive Phenology`)
fcm <- bind_rows(read_csv("data/FCM analyses - TREEMUTATION.csv"),
                 read_csv("data/Results of FCM analyses - TREEMUTATION.csv")) %>% 
  rename(GenomeMbp = `1C (Mbp)`)
species <- left_join(species, fcm)
```

# Species

```{r tablespecies}
species %>% 
  filter(TreeAdapt == 1) %>% 
  # filter(!is.na(AnnualRings))  %>% 
  dplyr::select(Family, Genus, Species, AnnualRings, ReproductivePhenology, ID, GenomeMbp) %>% 
  unique() %>% 
  DT::datatable(colnames = c("Family", "Genus", "Species", "Annual rings", "Reproductive phenology", "Sample", "Genome (Mbp)"))
```

